[
{ "tag": "const", "name": "BAR", "location": "example.h:5:11", "type": { "tag": ":int" }, "value": 14 },
{ "tag": "extern", "name": "SomeExtern", "location": "example.h:7:12", "type": { "tag": ":int" } },
{ "tag": "function", "name": "blah", "location": "example.h:9:6", "parameters": [{ "tag": "parameter", "name": "x", "type": { "tag": ":pointer", "type": { "tag": ":pointer", "type": { "tag": ":char" } } } }], "return-type": { "tag": ":void" } },
{ "tag": "extern", "name": "foo", "location": "example.h:11:14", "type": { "tag": ":pointer", "type": { "tag": ":char" } } },
{ "tag": "struct", "name": "my_point", "location": "example.h:13:16", "fields": [{ "tag": "field", "name": "x", "type": { "tag": ":int" } }, { "tag": "field", "name": "y", "type": { "tag": ":int" } }, { "tag": "field", "name": "odd_value", "type": { "tag": ":array", "type": { "tag": ":int" }, "size": 15 } }] },
{ "tag": "typedef", "name": "my_point_t", "location": "example.h:17:3", "type": { "tag": "struct", "name": "my_point", "location": "example.h:13:16", "fields": [{ "tag": "field", "name": "x", "type": { "tag": ":int" } }, { "tag": "field", "name": "y", "type": { "tag": ":int" } }, { "tag": "field", "name": "odd_value", "type": { "tag": ":array", "type": { "tag": ":int" }, "size": 15 } }] } },
{ "tag": "typedef", "name": "anonymous_t", "location": "example.h:21:3", "type": { "tag": "struct", "name": "", "location": "example.h:19:9", "fields": [{ "tag": "field", "name": "a", "type": { "tag": ":int" } }, { "tag": "field", "name": "b", "type": { "tag": ":int" } }] } },
{ "tag": "struct", "name": "some_struct", "location": "example.h:23:16", "fields": [{ "tag": "field", "name": "s", "type": { "tag": "struct", "name": "_some_internal_struct", "location": "example.h:24:10", "fields": [{ "tag": "field", "name": "a", "type": { "tag": "struct", "name": "", "location": "example.h:25:5", "fields": [{ "tag": "field", "name": "x", "type": { "tag": ":double" } }] } }, { "tag": "field", "name": "x", "type": { "tag": ":int" } }, { "tag": "field", "name": "c", "type": { "tag": ":char" } }, { "tag": "field", "name": "m", "type": { "tag": "enum", "name": "", "location": "example.h:31:5", "fields": [{ "tag": "field", "name": "X", "value": 0 }, { "tag": "field", "name": "Y", "value": 1 }, { "tag": "field", "name": "Z", "value": 2 }] } }] } }, { "tag": "field", "name": "blah", "type": { "tag": ":int" } }] },
{ "tag": "typedef", "name": "some_struct_t", "location": "example.h:37:3", "type": { "tag": "struct", "name": "some_struct", "location": "example.h:23:16", "fields": [{ "tag": "field", "name": "s", "type": { "tag": "struct", "name": "_some_internal_struct", "location": "example.h:24:10", "fields": [{ "tag": "field", "name": "a", "type": { "tag": "struct", "name": "", "location": "example.h:25:5", "fields": [{ "tag": "field", "name": "x", "type": { "tag": ":double" } }] } }, { "tag": "field", "name": "x", "type": { "tag": ":int" } }, { "tag": "field", "name": "c", "type": { "tag": ":char" } }, { "tag": "field", "name": "m", "type": { "tag": "enum", "name": "", "location": "example.h:31:5", "fields": [{ "tag": "field", "name": "X", "value": 0 }, { "tag": "field", "name": "Y", "value": 1 }, { "tag": "field", "name": "Z", "value": 2 }] } }] } }, { "tag": "field", "name": "blah", "type": { "tag": ":int" } }] } },
{ "tag": "union", "name": "my_union", "location": "example.h:39:7", "fields": [{ "tag": "field", "name": "c", "type": { "tag": ":char" } }, { "tag": "field", "name": "i", "type": { "tag": ":int" } }, { "tag": "field", "name": "d", "type": { "tag": ":double" } }] },
{ "tag": "enum", "name": "some_values", "location": "example.h:45:6", "fields": [{ "tag": "field", "name": "a_value", "value": 0 }, { "tag": "field", "name": "another_value", "value": 1 }, { "tag": "field", "name": "yet_another_value", "value": 2 }] },
{ "tag": "function", "name": "do_something", "location": "example.h:51:6", "parameters": [{ "tag": "parameter", "name": "p", "type": { "tag": ":pointer", "type": { "tag": "my_point_t" } } }, { "tag": "parameter", "name": "x", "type": { "tag": ":int" } }, { "tag": "parameter", "name": "y", "type": { "tag": ":int" } }], "return-type": { "tag": ":void" } }
]
